// 「行き先」に出す国と、国ごとの地域（都市）の一覧。
// 国は、海外在留邦人数調査の国・地域の並び（地方ごと）のまま載せる。
// 地域は人口の多い都市を中心に5つ程度（アメリカなど大きな国は多め、小さな国は無し）。
// 地域のキーワードはその国の投稿の中だけで探すので、他の国の地名と重なっても構わない。
// ただし「パリ」「バリ」のように、ふつうの言葉の一部になりやすい短い地名は、
// 誤って振り分けないよう、長い形（「バリ島」など）にしている
import type { Place, Region } from './data';

// 表示名の「 / 」で区切った名前は、そのままキーワードにもなる
// ignore の言葉は、探す前に本文から取り除く（「ポルトガル」を「ポルト」と数えないためなど）
function city(slug: string, name: string, extra: string[] = [], ignore: string[] = []): Region {
  return { slug, name, keywords: [...name.split(' / '), ...extra], ignore };
}

type Area = Place['area'];

function country(
  slug: string,
  name: string,
  area: Area,
  regions: Region[] = [],
  aliases: string[] = []
): Place {
  return { slug, name, flag: slug, area, regions, aliases };
}

export const PLACES: Place[] = [
  // アジア
  country('in', 'インド', 'asia', [
    city('delhi-gurgaon', 'デリー / グルガオン', [
      'グルグラム',
      'ノイダ',
      'Delhi',
      'Gurgaon',
      'Gurugram',
      'Noida',
    ]),
    city('mumbai', 'ムンバイ', ['Mumbai']),
    city('bangalore', 'バンガロール', ['ベンガルール', 'Bangalore', 'Bengaluru']),
    city('chennai', 'チェンナイ', ['Chennai']),
    city('hyderabad', 'ハイデラバード', ['Hyderabad']),
    city('kolkata', 'コルカタ', ['カルカッタ', 'Kolkata']),
    city('pune', 'プネー', ['プネ', 'Pune']),
    city('ahmedabad', 'アーメダバード', ['アフマダーバード', 'Ahmedabad']),
  ]),
  country('id', 'インドネシア', 'asia', [
    city('jakarta', 'ジャカルタ', ['チカラン', 'ブカシ', 'Jakarta', 'Cikarang', 'Bekasi']),
    city('surabaya', 'スラバヤ', ['Surabaya']),
    city('bandung', 'バンドン', ['Bandung']),
    city('medan', 'メダン', ['Medan']),
    city('bali', 'バリ島 / デンパサール', ['Bali', 'Denpasar']),
  ]),
  country('kh', 'カンボジア', 'asia', [
    city('phnom-penh', 'プノンペン', ['Phnom Penh']),
    city('siem-reap', 'シェムリアップ', ['Siem Reap']),
    city('sihanoukville', 'シアヌークビル', ['Sihanoukville']),
    city('battambang', 'バッタンバン', ['Battambang']),
  ]),
  country('sg', 'シンガポール', 'asia'),
  country('lk', 'スリランカ', 'asia', [
    city('colombo', 'コロンボ', ['Colombo']),
    city('kandy', 'キャンディ', ['Kandy']),
    city('negombo', 'ネゴンボ', ['Negombo']),
  ]),
  country('th', 'タイ', 'asia', [
    city('bangkok', 'バンコク', ['Bangkok']),
    city('chonburi', 'シラチャ / チョンブリ', [
      'シーラーチャー',
      'パタヤ',
      'Sriracha',
      'Chonburi',
      'Pattaya',
    ]),
    city('chiang-mai', 'チェンマイ', ['Chiang Mai']),
    city('ayutthaya', 'アユタヤ', ['Ayutthaya']),
    city('nakhon-ratchasima', 'コラート / ナコンラチャシマ', ['Korat', 'Nakhon Ratchasima']),
    city('phuket', 'プーケット', ['Phuket']),
  ]),
  country('kr', '韓国', 'asia', [
    city('seoul', 'ソウル', ['Seoul']),
    city('busan', '釜山', ['プサン', 'Busan']),
    city('incheon', '仁川', ['インチョン', 'Incheon']),
    city('daegu', '大邱', ['Daegu']),
    city('daejeon', '大田', ['テジョン', 'Daejeon']),
  ]),
  country('tw', '台湾', 'asia', [
    city('taipei', '台北', ['臺北', 'タイペイ', 'Taipei']),
    city('new-taipei', '新北', ['New Taipei']),
    city('taichung', '台中', ['臺中', 'Taichung']),
    city('kaohsiung', '高雄', ['Kaohsiung']),
    city('tainan', '台南', ['臺南', 'Tainan']),
    city('taoyuan', '桃園', ['Taoyuan']),
  ]),
  country('cn', '中国', 'asia', [
    city('shanghai', '上海', ['Shanghai']),
    city('beijing', '北京', ['Beijing']),
    city('guangzhou-shenzhen', '広州 / 深圳', ['深セン', 'Guangzhou', 'Shenzhen']),
    city('chongqing', '重慶', ['Chongqing']),
    city('chengdu', '成都', ['Chengdu']),
    city('tianjin', '天津', ['Tianjin']),
    city('wuhan', '武漢', ['Wuhan']),
    city('suzhou', '蘇州', ['Suzhou']),
    city('dalian', '大連', ['Dalian']),
  ]),
  country('np', 'ネパール', 'asia', [
    city('kathmandu', 'カトマンズ', ['Kathmandu']),
    city('pokhara', 'ポカラ', ['Pokhara']),
    city('lalitpur', 'パタン / ラリトプル', ['Lalitpur']),
  ]),
  country('pk', 'パキスタン', 'asia', [
    city('karachi', 'カラチ', ['Karachi']),
    city('lahore', 'ラホール', ['Lahore']),
    city('islamabad', 'イスラマバード', ['Islamabad']),
    city('faisalabad', 'ファイサラバード', ['Faisalabad']),
    city('rawalpindi', 'ラワルピンディ', ['Rawalpindi']),
  ]),
  country('bd', 'バングラデシュ', 'asia', [
    city('dhaka', 'ダッカ', ['Dhaka']),
    city('chittagong', 'チッタゴン', ['チャットグラム', 'Chittagong', 'Chattogram']),
    city('khulna', 'クルナ', ['Khulna']),
  ]),
  country('tl', '東ティモール', 'asia', [city('dili', 'ディリ', ['Dili'])]),
  country('ph', 'フィリピン', 'asia', [
    city('manila', 'マニラ', ['マカティ', 'タギッグ', 'ケソン', 'パサイ', 'Manila', 'Makati', 'Taguig', 'BGC']),
    city('cebu', 'セブ', ['Cebu'], ['セブン']),
    city('davao', 'ダバオ', ['Davao']),
    city('clark', 'クラーク / アンヘレス', ['Angeles City']),
    city('calabarzon', 'カビテ / ラグナ / バタンガス', ['Cavite', 'Laguna', 'Batangas']),
  ]),
  country('bt', 'ブータン', 'asia', [city('thimphu', 'ティンプー', ['Thimphu'])]),
  country('bn', 'ブルネイ', 'asia', [city('bandar-seri-begawan', 'バンダルスリブガワン', ['Bandar Seri Begawan'])]),
  country('vn', 'ベトナム', 'asia', [
    city('ho-chi-minh', 'ホーチミン', ['サイゴン', 'Ho Chi Minh', 'Saigon']),
    city('hanoi', 'ハノイ', ['Hanoi']),
    city('da-nang', 'ダナン', ['Da Nang', 'Danang']),
    city('hai-phong', 'ハイフォン', ['Hai Phong', 'Haiphong']),
    city('can-tho', 'カントー', ['Can Tho']),
  ]),
  country('my', 'マレーシア', 'asia', [
    city('kuala-lumpur', 'クアラルンプール', ['Kuala Lumpur']),
    city('johor-bahru', 'ジョホールバル', ['ジョホール・バル', 'Johor Bahru']),
    city('penang', 'ペナン', ['ジョージタウン', 'Penang', 'George Town']),
    city('ipoh', 'イポー', ['Ipoh']),
    city('kota-kinabalu', 'コタキナバル', ['Kota Kinabalu']),
  ]),
  country('mm', 'ミャンマー', 'asia', [
    city('yangon', 'ヤンゴン', ['Yangon']),
    city('mandalay', 'マンダレー', ['Mandalay']),
    city('naypyidaw', 'ネピドー', ['Naypyidaw']),
  ]),
  country('mv', 'モルディブ', 'asia'),
  country('mn', 'モンゴル', 'asia', [
    city('ulaanbaatar', 'ウランバートル', ['Ulaanbaatar', 'Ulan Bator']),
    city('erdenet', 'エルデネト', ['Erdenet']),
  ]),
  country('la', 'ラオス', 'asia', [
    city('vientiane', 'ビエンチャン', ['Vientiane']),
    city('luang-prabang', 'ルアンパバーン', ['ルアンプラバン', 'Luang Prabang']),
    city('pakse', 'パクセー', ['Pakse']),
  ]),

  // 大洋州
  country('au', 'オーストラリア', 'oceania', [
    city('sydney', 'シドニー', ['Sydney']),
    city('melbourne', 'メルボルン', ['Melbourne']),
    city('brisbane', 'ブリスベン', ['Brisbane']),
    city('perth', 'パース', ['Perth']),
    city('adelaide', 'アデレード', ['Adelaide']),
    city('gold-coast', 'ゴールドコースト', ['Gold Coast']),
    city('cairns', 'ケアンズ', ['Cairns']),
  ]),
  country('mp', '北マリアナ諸島（米領・サイパン）', 'oceania', [], ['北マリアナ諸島', 'サイパン']),
  country('ki', 'キリバス', 'oceania'),
  country('gu', 'グアム（米領）', 'oceania', [], ['グアム']),
  country('ck', 'クック諸島', 'oceania'),
  country('as', 'サモア（米領）', 'oceania', [], ['米領サモア']),
  country('ws', 'サモア独立国', 'oceania', [], ['サモア']),
  country('sb', 'ソロモン諸島', 'oceania'),
  country('tv', 'ツバル', 'oceania'),
  country('to', 'トンガ', 'oceania'),
  country('nr', 'ナウル', 'oceania'),
  country('nu', 'ニウエ', 'oceania'),
  country('nc', 'ニューカレドニア（仏領）', 'oceania', [], ['ニューカレドニア']),
  country('nz', 'ニュージーランド', 'oceania', [
    city('auckland', 'オークランド', ['Auckland']),
    city('wellington', 'ウェリントン', ['Wellington']),
    city('christchurch', 'クライストチャーチ', ['Christchurch']),
    city('hamilton', 'ハミルトン', ['Hamilton']),
    city('tauranga', 'タウランガ', ['Tauranga']),
    city('queenstown', 'クイーンズタウン', ['Queenstown']),
  ]),
  country('vu', 'バヌアツ', 'oceania'),
  country('pg', 'パプアニューギニア', 'oceania', [
    city('port-moresby', 'ポートモレスビー', ['Port Moresby']),
  ]),
  country('pw', 'パラオ', 'oceania'),
  country('fj', 'フィジー', 'oceania'),
  country('pf', 'ポリネシア（仏領・タヒチ）', 'oceania', [], ['タヒチ', '仏領ポリネシア']),
  country('mh', 'マーシャル', 'oceania', [], ['マーシャル諸島']),
  country('fm', 'ミクロネシア', 'oceania', [], ['ミクロネシア連邦']),

  // 北米
  country(
    'us',
    'アメリカ',
    'north-america',
    [
      city('new-york', 'ニューヨーク / ニュージャージー', ['New York', 'New Jersey']),
      city('los-angeles', 'ロサンゼルス', ['トーランス', 'Los Angeles', 'Torrance']),
      city('bay-area', 'サンフランシスコ / ベイエリア', [
        'シリコンバレー',
        'サンノゼ',
        'San Francisco',
        'Bay Area',
        'San Jose',
      ]),
      city('chicago', 'シカゴ', ['Chicago']),
      city('houston', 'ヒューストン', ['Houston']),
      city('dallas', 'ダラス', ['フォートワース', 'Dallas', 'Fort Worth']),
      city('phoenix', 'フェニックス', ['Phoenix']),
      city('philadelphia', 'フィラデルフィア', ['Philadelphia']),
      city('san-diego', 'サンディエゴ', ['San Diego']),
      city('seattle', 'シアトル', ['Seattle']),
      city('atlanta', 'アトランタ', ['Atlanta']),
      city('washington-dc', 'ワシントンDC', ['ワシントンD.C.', 'Washington DC', 'Washington, D.C.']),
      city('boston', 'ボストン', ['Boston']),
      city('detroit', 'デトロイト', ['Detroit']),
      city('hawaii', 'ハワイ / ホノルル', ['Hawaii', 'Honolulu']),
    ],
    ['米国']
  ),
  country('ca', 'カナダ', 'north-america', [
    city('toronto', 'トロント', ['Toronto']),
    city('montreal', 'モントリオール', ['Montreal']),
    city('vancouver', 'バンクーバー', ['Vancouver']),
    city('calgary', 'カルガリー', ['Calgary']),
    city('ottawa', 'オタワ', ['Ottawa']),
    city('edmonton', 'エドモントン', ['Edmonton']),
  ]),
  country('gl', 'グリーンランド（デンマーク領）', 'north-america', [], ['グリーンランド']),

  // 中南米
  country('aw', 'アルバ（蘭領）', 'latin-america', [], ['アルバ']),
  country('ag', 'アンティグア・バーブーダ', 'latin-america'),
  country('sv', 'エルサルバドル', 'latin-america', [
    city('san-salvador', 'サンサルバドル', ['サン・サルバドル', 'San Salvador']),
    city('santa-ana', 'サンタアナ', ['Santa Ana']),
  ]),
  country('cw', 'キュラソー（蘭領）', 'latin-america', [], ['キュラソー']),
  country('cu', 'キューバ', 'latin-america', [
    city('havana', 'ハバナ', ['Havana']),
    city('santiago-de-cuba', 'サンティアゴ・デ・クーバ', ['Santiago de Cuba']),
  ]),
  country('gt', 'グアテマラ', 'latin-america', [
    city('guatemala-city', 'グアテマラシティ', ['グアテマラ市', 'Guatemala City']),
    city('antigua', 'アンティグア', ['Antigua']),
    city('quetzaltenango', 'ケツァルテナンゴ', ['Quetzaltenango']),
  ]),
  country('gp', 'グアドループ（仏領）', 'latin-america', [], ['グアドループ']),
  country('gd', 'グレナダ', 'latin-america'),
  country('cr', 'コスタリカ', 'latin-america', [
    city('san-jose', 'サンホセ', ['サン・ホセ', 'San José', 'San Jose']),
    city('alajuela', 'アラフエラ', ['Alajuela']),
    city('liberia', 'リベリア', ['Liberia']),
  ]),
  country('bl', 'サン・バルテルミー（仏領）', 'latin-america', [], ['サン・バルテルミー']),
  country('mf', 'サン・マルタン（仏領）', 'latin-america', [], ['サン・マルタン']),
  country('jm', 'ジャマイカ', 'latin-america', [
    city('kingston', 'キングストン', ['Kingston']),
    city('montego-bay', 'モンテゴベイ', ['Montego Bay']),
  ]),
  country('sx', 'シント・マールテン（蘭領）', 'latin-america', [], ['シント・マールテン']),
  country('kn', 'セントクリストファー・ネービス', 'latin-america'),
  country('vc', 'セントビンセント及びグレナディーン諸島', 'latin-america'),
  country('lc', 'セントルシア', 'latin-america'),
  country('dm', 'ドミニカ国', 'latin-america'),
  country('do', 'ドミニカ共和国', 'latin-america', [
    city('santo-domingo', 'サントドミンゴ', ['Santo Domingo']),
    city('santiago', 'サンティアゴ', ['Santiago']),
    city('punta-cana', 'プンタカナ', ['Punta Cana']),
  ]),
  country('tt', 'トリニダード・トバゴ', 'latin-america', [
    city('port-of-spain', 'ポートオブスペイン', ['Port of Spain']),
  ]),
  country('ni', 'ニカラグア', 'latin-america', [
    city('managua', 'マナグア', ['Managua']),
    city('leon', 'レオン', ['León']),
    city('granada', 'グラナダ', ['Granada']),
  ]),
  country('vi', 'バージン諸島（米領）', 'latin-america', [], ['米領バージン諸島']),
  country('ht', 'ハイチ', 'latin-america', [city('port-au-prince', 'ポルトープランス', ['Port-au-Prince'])]),
  country('pa', 'パナマ', 'latin-america', [
    city('panama-city', 'パナマシティ', ['パナマ市', 'Panama City']),
  ]),
  country('bs', 'バハマ', 'latin-america', [city('nassau', 'ナッソー', ['Nassau'])]),
  country('bb', 'バルバドス', 'latin-america'),
  country('pr', 'プエルトリコ（米領）', 'latin-america', [], ['プエルトリコ']),
  country('bz', 'ベリーズ', 'latin-america', [
    city('belize-city', 'ベリーズシティ', ['Belize City']),
    city('belmopan', 'ベルモパン', ['Belmopan']),
  ]),
  country('hn', 'ホンジュラス', 'latin-america', [
    city('tegucigalpa', 'テグシガルパ', ['Tegucigalpa']),
    city('san-pedro-sula', 'サンペドロスーラ', ['San Pedro Sula']),
  ]),
  country('mq', 'マルチニーク（仏領）', 'latin-america', [], ['マルチニーク']),
  country('mx', 'メキシコ', 'latin-america', [
    city('mexico-city', 'メキシコシティ', ['メキシコ市', 'Mexico City', 'CDMX']),
    city('guadalajara', 'グアダラハラ', ['Guadalajara']),
    city('monterrey', 'モンテレイ', ['Monterrey']),
    city('bajio', 'レオン / グアナファト / ケレタロ', [
      'アグアスカリエンテス',
      'シラオ',
      'イラプアト',
      'León',
      'Guanajuato',
      'Querétaro',
      'Queretaro',
      'Aguascalientes',
    ]),
    city('puebla', 'プエブラ', ['Puebla']),
    city('tijuana', 'ティフアナ', ['Tijuana']),
    city('cancun', 'カンクン', ['Cancún', 'Cancun']),
  ]),
  country('ar', 'アルゼンチン', 'latin-america', [
    city('buenos-aires', 'ブエノスアイレス', ['Buenos Aires']),
    city('cordoba', 'コルドバ', ['Córdoba', 'Cordoba']),
    city('rosario', 'ロサリオ', ['Rosario']),
    city('mendoza', 'メンドーサ', ['Mendoza']),
    city('la-plata', 'ラプラタ', ['La Plata']),
  ]),
  country('uy', 'ウルグアイ', 'latin-america', [
    city('montevideo', 'モンテビデオ', ['Montevideo']),
    city('punta-del-este', 'プンタデルエステ', ['Punta del Este']),
  ]),
  country('ec', 'エクアドル', 'latin-america', [
    city('guayaquil', 'グアヤキル', ['Guayaquil']),
    city('quito', 'キト', ['Quito'], ['テキトー', 'テキトウ']),
    city('cuenca', 'クエンカ', ['Cuenca']),
  ]),
  country('gy', 'ガイアナ', 'latin-america', [city('georgetown', 'ジョージタウン', ['Georgetown'])]),
  country('gf', 'ギアナ（仏領）', 'latin-america', [], ['仏領ギアナ']),
  country('co', 'コロンビア', 'latin-america', [
    city('bogota', 'ボゴタ', ['Bogotá', 'Bogota']),
    city('medellin', 'メデジン', ['Medellín', 'Medellin']),
    city('barranquilla', 'バランキージャ', ['Barranquilla']),
    city('cartagena', 'カルタヘナ', ['Cartagena']),
  ]),
  country('sr', 'スリナム', 'latin-america', [city('paramaribo', 'パラマリボ', ['Paramaribo'])]),
  country('cl', 'チリ', 'latin-america', [
    city('santiago', 'サンティアゴ', ['Santiago']),
    city('valparaiso', 'バルパライソ / ビニャデルマール', ['Valparaíso', 'Valparaiso', 'Viña del Mar']),
    city('concepcion', 'コンセプシオン', ['Concepción']),
    city('antofagasta', 'アントファガスタ', ['Antofagasta']),
  ]),
  country('py', 'パラグアイ', 'latin-america', [
    city('asuncion', 'アスンシオン', ['Asunción', 'Asuncion']),
    city('ciudad-del-este', 'シウダーデルエステ', ['Ciudad del Este']),
    city('encarnacion', 'エンカルナシオン', ['Encarnación', 'Encarnacion']),
    city('pirapo', 'ピラポ / イグアス移住地', ['Pirapó', 'Yguazú']),
  ]),
  country('br', 'ブラジル', 'latin-america', [
    city('sao-paulo', 'サンパウロ', ['São Paulo', 'Sao Paulo']),
    city('rio-de-janeiro', 'リオデジャネイロ', ['リオ・デ・ジャネイロ', 'Rio de Janeiro']),
    city('brasilia', 'ブラジリア', ['Brasília', 'Brasilia']),
    city('salvador', 'サルバドール', ['Salvador']),
    city('fortaleza', 'フォルタレザ', ['Fortaleza']),
    city('belo-horizonte', 'ベロオリゾンテ', ['Belo Horizonte']),
    city('curitiba', 'クリチバ', ['Curitiba']),
    city('manaus', 'マナウス', ['Manaus']),
  ]),
  country('ve', 'ベネズエラ', 'latin-america', [
    city('caracas', 'カラカス', ['Caracas']),
    city('maracaibo', 'マラカイボ', ['Maracaibo']),
    city('valencia', 'バレンシア', ['Valencia']),
  ]),
  country('pe', 'ペルー', 'latin-america', [
    city('lima', 'リマ', [], ['リマインド']),
    city('arequipa', 'アレキパ', ['Arequipa']),
    city('trujillo', 'トルヒーヨ', ['Trujillo']),
    city('cusco', 'クスコ', ['Cusco', 'Cuzco']),
  ]),
  country('bo', 'ボリビア', 'latin-america', [
    city('santa-cruz', 'サンタクルス', ['Santa Cruz']),
    city('la-paz', 'ラパス', ['La Paz']),
    city('cochabamba', 'コチャバンバ', ['Cochabamba']),
    city('sucre', 'スクレ', ['Sucre']),
  ]),

  // 欧州
  country('is', 'アイスランド', 'europe', [city('reykjavik', 'レイキャビク', ['Reykjavík', 'Reykjavik'])]),
  country('ie', 'アイルランド', 'europe', [
    city('dublin', 'ダブリン', ['Dublin']),
    city('galway', 'ゴールウェイ', ['Galway']),
    city('limerick', 'リムリック', ['Limerick']),
  ]),
  country('ad', 'アンドラ', 'europe'),
  country('it', 'イタリア', 'europe', [
    city('rome', 'ローマ', [], ['ローマ字']),
    city('milan', 'ミラノ', ['Milano', 'Milan']),
    city('naples', 'ナポリ', ['Napoli', 'Naples']),
    city('turin', 'トリノ', ['Torino', 'Turin']),
    city('florence', 'フィレンツェ', ['Firenze', 'Florence']),
    city('palermo', 'パレルモ', ['Palermo']),
  ]),
  country(
    'gb',
    'イギリス',
    'europe',
    [
      city('london', 'ロンドン', ['London']),
      city('birmingham', 'バーミンガム', ['Birmingham']),
      city('manchester', 'マンチェスター', ['Manchester']),
      city('glasgow', 'グラスゴー', ['Glasgow']),
      city('edinburgh', 'エディンバラ', ['エジンバラ', 'Edinburgh']),
    ],
    ['英国']
  ),
  country('ee', 'エストニア', 'europe', [
    city('tallinn', 'タリン', ['Tallinn']),
    city('tartu', 'タルトゥ', ['Tartu']),
  ]),
  country('at', 'オーストリア', 'europe', [
    city('vienna', 'ウィーン', ['Wien', 'Vienna']),
    city('graz', 'グラーツ', ['Graz']),
    city('linz', 'リンツ', ['Linz']),
    city('salzburg', 'ザルツブルク', ['Salzburg']),
    city('innsbruck', 'インスブルック', ['Innsbruck']),
  ]),
  country('nl', 'オランダ', 'europe', [
    city('amsterdam', 'アムステルダム / アムステルフェーン', ['Amsterdam', 'Amstelveen']),
    city('rotterdam', 'ロッテルダム', ['Rotterdam']),
    city('the-hague', 'ハーグ', ['デン・ハーグ', 'Den Haag', 'The Hague']),
    city('utrecht', 'ユトレヒト', ['Utrecht']),
    city('eindhoven', 'アイントホーフェン', ['アイントホーヘン', 'Eindhoven']),
  ]),
  country('cy', 'キプロス', 'europe', [
    city('nicosia', 'ニコシア', ['Nicosia']),
    city('limassol', 'リマソール', ['Limassol']),
    city('larnaca', 'ラルナカ', ['Larnaca']),
  ]),
  country('gr', 'ギリシャ', 'europe', [
    city('athens', 'アテネ', ['Athens']),
    city('thessaloniki', 'テッサロニキ', ['Thessaloniki']),
    city('patras', 'パトラ', ['Patras']),
  ]),
  country('sm', 'サンマリノ', 'europe'),
  country('ch', 'スイス', 'europe', [
    city('zurich', 'チューリッヒ', ['Zürich', 'Zurich']),
    city('geneva', 'ジュネーブ', ['Genève', 'Geneva']),
    city('basel', 'バーゼル', ['Basel']),
    city('lausanne', 'ローザンヌ', ['Lausanne']),
    city('bern', 'ベルン', ['Bern']),
  ]),
  country('se', 'スウェーデン', 'europe', [
    city('stockholm', 'ストックホルム', ['Stockholm']),
    city('gothenburg', 'ヨーテボリ', ['イェーテボリ', 'Göteborg', 'Gothenburg']),
    city('malmo', 'マルメ', ['Malmö', 'Malmo']),
    city('uppsala', 'ウプサラ', ['Uppsala']),
  ]),
  country('es', 'スペイン', 'europe', [
    city('madrid', 'マドリード', ['マドリッド', 'Madrid']),
    city('barcelona', 'バルセロナ', ['Barcelona']),
    city('valencia', 'バレンシア', ['Valencia']),
    city('seville', 'セビリア', ['Sevilla', 'Seville']),
    city('malaga', 'マラガ', ['Málaga', 'Malaga']),
  ]),
  country('dk', 'デンマーク', 'europe', [
    city('copenhagen', 'コペンハーゲン', ['Copenhagen', 'København']),
    city('aarhus', 'オーフス', ['Aarhus']),
    city('odense', 'オーデンセ', ['Odense']),
  ]),
  country('de', 'ドイツ', 'europe', [
    city('berlin', 'ベルリン', ['Berlin']),
    city('hamburg', 'ハンブルク', ['ハンブルグ', 'Hamburg']),
    city('munich', 'ミュンヘン', ['München', 'Munich']),
    city('cologne', 'ケルン', ['Köln', 'Cologne']),
    city('frankfurt', 'フランクフルト', ['Frankfurt']),
    city('dusseldorf', 'デュッセルドルフ', ['Düsseldorf', 'Dusseldorf']),
    city('stuttgart', 'シュトゥットガルト', ['Stuttgart']),
  ]),
  country('no', 'ノルウェー', 'europe', [
    city('oslo', 'オスロ', ['Oslo']),
    city('bergen', 'ベルゲン', ['Bergen']),
    city('trondheim', 'トロンハイム', ['Trondheim']),
    city('stavanger', 'スタヴァンゲル', ['スタバンゲル', 'Stavanger']),
  ]),
  country('va', 'バチカン', 'europe'),
  country('fi', 'フィンランド', 'europe', [
    city('helsinki', 'ヘルシンキ', ['Helsinki']),
    city('espoo', 'エスポー', ['Espoo']),
    city('tampere', 'タンペレ', ['Tampere']),
    city('turku', 'トゥルク', ['Turku']),
    city('oulu', 'オウル', ['Oulu']),
  ]),
  country('fo', 'フェロー諸島（デンマーク領）', 'europe', [], ['フェロー諸島']),
  country('fr', 'フランス', 'europe', [
    city('paris', 'パリ', ['Paris']),
    city('marseille', 'マルセイユ', ['Marseille']),
    city('lyon', 'リヨン', ['Lyon']),
    city('toulouse', 'トゥールーズ', ['Toulouse']),
    city('nice', 'ニース'),
    city('strasbourg', 'ストラスブール', ['Strasbourg']),
  ]),
  country('be', 'ベルギー', 'europe', [
    city('brussels', 'ブリュッセル', ['Bruxelles', 'Brussels']),
    city('antwerp', 'アントワープ', ['アントウェルペン', 'Antwerpen', 'Antwerp']),
    city('ghent', 'ゲント', ['Ghent']),
    city('liege', 'リエージュ', ['Liège']),
  ]),
  country('pt', 'ポルトガル', 'europe', [
    city('lisbon', 'リスボン', ['Lisboa', 'Lisbon']),
    city('porto', 'ポルト', ['Porto'], ['ポルトガル']),
    city('braga', 'ブラガ', ['Braga']),
    city('coimbra', 'コインブラ', ['Coimbra']),
  ]),
  country('mt', 'マルタ', 'europe'),
  country('mc', 'モナコ', 'europe'),
  country('lv', 'ラトビア', 'europe', [city('riga', 'リガ', ['Riga'])]),
  country('lt', 'リトアニア', 'europe', [
    city('vilnius', 'ビリニュス', ['ヴィリニュス', 'Vilnius']),
    city('kaunas', 'カウナス', ['Kaunas']),
  ]),
  country('li', 'リヒテンシュタイン', 'europe'),
  country('lu', 'ルクセンブルク', 'europe'),
  country('az', 'アゼルバイジャン', 'europe', [city('baku', 'バクー', ['Baku'])]),
  country('al', 'アルバニア', 'europe', [
    city('tirana', 'ティラナ', ['Tirana']),
    city('durres', 'ドゥラス', ['Durrës']),
  ]),
  country('am', 'アルメニア', 'europe', [city('yerevan', 'エレバン', ['Yerevan'])]),
  country('uz', 'ウズベキスタン', 'europe', [
    city('tashkent', 'タシケント', ['Tashkent']),
    city('samarkand', 'サマルカンド', ['Samarkand']),
    city('bukhara', 'ブハラ', ['Bukhara']),
  ]),
  country('kz', 'カザフスタン', 'europe', [
    city('almaty', 'アルマティ', ['Almaty']),
    city('astana', 'アスタナ', ['Astana']),
    city('shymkent', 'シムケント', ['Shymkent']),
  ]),
  country('mk', '北マケドニア', 'europe', [city('skopje', 'スコピエ', ['Skopje'])]),
  country('kg', 'キルギス', 'europe', [
    city('bishkek', 'ビシュケク', ['Bishkek']),
    city('osh', 'オシュ'),
  ]),
  country('hr', 'クロアチア', 'europe', [
    city('zagreb', 'ザグレブ', ['Zagreb']),
    city('split', 'スプリト'),
    city('rijeka', 'リエカ', ['Rijeka']),
    city('dubrovnik', 'ドブロブニク', ['ドゥブロヴニク', 'Dubrovnik']),
  ]),
  country('xk', 'コソボ', 'europe', [city('pristina', 'プリシュティナ', ['Pristina'])]),
  country('ge', 'ジョージア', 'europe', [
    city('tbilisi', 'トビリシ', ['Tbilisi']),
    city('batumi', 'バトゥミ', ['Batumi']),
    city('kutaisi', 'クタイシ', ['Kutaisi']),
  ]),
  country('sk', 'スロバキア', 'europe', [
    city('bratislava', 'ブラチスラバ', ['Bratislava']),
    city('kosice', 'コシツェ', ['Košice', 'Kosice']),
  ]),
  country('si', 'スロベニア', 'europe', [
    city('ljubljana', 'リュブリャナ', ['Ljubljana']),
    city('maribor', 'マリボル', ['Maribor']),
  ]),
  country('rs', 'セルビア', 'europe', [
    city('belgrade', 'ベオグラード', ['Belgrade', 'Beograd']),
    city('novi-sad', 'ノヴィ・サド', ['ノビサド', 'Novi Sad']),
    city('nis', 'ニシュ'),
  ]),
  country('tj', 'タジキスタン', 'europe', [city('dushanbe', 'ドゥシャンベ', ['Dushanbe'])]),
  country('cz', 'チェコ', 'europe', [
    city('prague', 'プラハ', ['Praha', 'Prague']),
    city('brno', 'ブルノ', ['Brno']),
    city('ostrava', 'オストラバ', ['Ostrava']),
    city('plzen', 'プルゼニ', ['Plzeň', 'Plzen']),
  ]),
  country('tm', 'トルクメニスタン', 'europe', [city('ashgabat', 'アシガバット', ['Ashgabat'])]),
  country('hu', 'ハンガリー', 'europe', [
    city('budapest', 'ブダペスト', ['Budapest']),
    city('debrecen', 'デブレツェン', ['Debrecen']),
    city('szeged', 'セゲド', ['Szeged']),
    city('gyor', 'ジェール', ['Győr']),
  ]),
  country('bg', 'ブルガリア', 'europe', [
    city('sofia', 'ソフィア', ['Sofia']),
    city('plovdiv', 'プロブディフ', ['Plovdiv']),
    city('varna', 'ヴァルナ', ['バルナ', 'Varna']),
  ]),
  country('by', 'ベラルーシ', 'europe', [city('minsk', 'ミンスク', ['Minsk'])]),
  country('pl', 'ポーランド', 'europe', [
    city('warsaw', 'ワルシャワ', ['Warszawa', 'Warsaw']),
    city('krakow', 'クラクフ', ['Kraków', 'Krakow']),
    city('wroclaw', 'ヴロツワフ', ['ブロツワフ', 'Wrocław', 'Wroclaw']),
    city('lodz', 'ウッチ', ['Łódź', 'Lodz']),
    city('poznan', 'ポズナン', ['Poznań', 'Poznan']),
  ]),
  country('ba', 'ボスニア・ヘルツェゴビナ', 'europe', [
    city('sarajevo', 'サラエボ', ['Sarajevo']),
    city('banja-luka', 'バニャ・ルカ', ['Banja Luka']),
  ]),
  country('md', 'モルドバ', 'europe', [city('chisinau', 'キシナウ', ['Chișinău', 'Chisinau'])]),
  country('me', 'モンテネグロ', 'europe', [city('podgorica', 'ポドゴリツァ', ['Podgorica'])]),
  country('ro', 'ルーマニア', 'europe', [
    city('bucharest', 'ブカレスト', ['București', 'Bucharest']),
    city('cluj-napoca', 'クルジュ＝ナポカ', ['クルジュ', 'Cluj']),
    city('timisoara', 'ティミショアラ', ['Timișoara', 'Timisoara']),
  ]),
  country('ru', 'ロシア', 'europe', [
    city('moscow', 'モスクワ', ['Moscow']),
    city('saint-petersburg', 'サンクトペテルブルク', ['Saint Petersburg', 'St. Petersburg']),
    city('novosibirsk', 'ノボシビルスク', ['Novosibirsk']),
    city('yekaterinburg', 'エカテリンブルク', ['Yekaterinburg']),
    city('vladivostok', 'ウラジオストク', ['Vladivostok']),
    city('yuzhno-sakhalinsk', 'ユジノサハリンスク', ['Yuzhno-Sakhalinsk']),
  ]),

  // 中東
  country('ae', 'アラブ首長国連邦', 'middle-east', [
    city('dubai', 'ドバイ', ['Dubai']),
    city('abu-dhabi', 'アブダビ', ['Abu Dhabi']),
    city('sharjah', 'シャルジャ', ['Sharjah']),
  ]),
  country('ye', 'イエメン', 'middle-east', [city('sanaa', 'サヌア', ["Sana'a", 'Sanaa'])]),
  country('il', 'イスラエル', 'middle-east', [
    city('tel-aviv', 'テルアビブ', ['Tel Aviv']),
    city('jerusalem', 'エルサレム', ['Jerusalem']),
    city('haifa', 'ハイファ', ['Haifa']),
  ]),
  country('iq', 'イラク', 'middle-east', [
    city('baghdad', 'バグダッド', ['Baghdad']),
    city('erbil', 'アルビル', ['エルビル', 'Erbil']),
    city('basra', 'バスラ', ['Basra']),
  ]),
  country('ir', 'イラン', 'middle-east', [
    city('tehran', 'テヘラン', ['Tehran']),
    city('mashhad', 'マシュハド', ['Mashhad']),
    city('isfahan', 'イスファハン', ['エスファハーン', 'Isfahan']),
    city('shiraz', 'シーラーズ', ['Shiraz']),
    city('tabriz', 'タブリーズ', ['Tabriz']),
  ]),
  country('om', 'オマーン', 'middle-east', [city('muscat', 'マスカット', ['Muscat'])]),
  country('qa', 'カタール', 'middle-east', [city('doha', 'ドーハ', ['Doha'])]),
  country('kw', 'クウェート', 'middle-east'),
  country('sa', 'サウジアラビア', 'middle-east', [
    city('riyadh', 'リヤド', ['Riyadh']),
    city('jeddah', 'ジェッダ', ['Jeddah']),
    city('dammam', 'ダンマン / アル・コバール', ['Dammam', 'Khobar']),
    city('mecca', 'メッカ', ['Mecca']),
    city('medina', 'メディナ', ['Medina']),
  ]),
  country('tr', 'トルコ', 'middle-east', [
    city('istanbul', 'イスタンブール', ['Istanbul', 'İstanbul']),
    city('ankara', 'アンカラ', ['Ankara']),
    city('izmir', 'イズミル', ['İzmir', 'Izmir']),
    city('bursa', 'ブルサ', ['Bursa']),
    city('antalya', 'アンタルヤ', ['Antalya']),
  ]),
  country('bh', 'バーレーン', 'middle-east'),
  country('ps', 'パレスチナ', 'middle-east', [
    city('ramallah', 'ラマッラ', ['ラマラ', 'Ramallah']),
    city('gaza', 'ガザ', ['Gaza']),
  ]),
  country('jo', 'ヨルダン', 'middle-east', [
    city('amman', 'アンマン', ['Amman']),
    city('aqaba', 'アカバ', ['Aqaba']),
  ]),
  country('lb', 'レバノン', 'middle-east', [city('beirut', 'ベイルート', ['Beirut'])]),

  // アフリカ
  country('dz', 'アルジェリア', 'africa', [
    city('algiers', 'アルジェ', ['Algiers'], ['アルジェリア']),
  ]),
  country('ao', 'アンゴラ', 'africa', [city('luanda', 'ルアンダ', ['Luanda'])]),
  country('ug', 'ウガンダ', 'africa', [city('kampala', 'カンパラ', ['Kampala'])]),
  country('eg', 'エジプト', 'africa', [
    city('cairo', 'カイロ', ['Cairo', 'Giza'], ['カイロプラクティック']),
    city('alexandria', 'アレクサンドリア', ['Alexandria']),
    city('luxor', 'ルクソール', ['Luxor']),
  ]),
  country('sz', 'エスワティニ', 'africa'),
  country('et', 'エチオピア', 'africa', [city('addis-ababa', 'アディスアベバ', ['Addis Ababa'])]),
  country('er', 'エリトリア', 'africa'),
  country('gh', 'ガーナ', 'africa', [
    city('accra', 'アクラ', ['Accra']),
    city('kumasi', 'クマシ', ['Kumasi']),
  ]),
  country('cv', 'カーボベルデ', 'africa'),
  country('ga', 'ガボン', 'africa', [city('libreville', 'リーブルビル', ['Libreville'])]),
  country('cm', 'カメルーン', 'africa', [
    city('douala', 'ドゥアラ', ['Douala']),
    city('yaounde', 'ヤウンデ', ['Yaoundé', 'Yaounde']),
  ]),
  country('gm', 'ガンビア', 'africa'),
  country('gn', 'ギニア', 'africa', [city('conakry', 'コナクリ', ['Conakry'])]),
  country('gw', 'ギニアビサウ', 'africa'),
  country('ke', 'ケニア', 'africa', [
    city('nairobi', 'ナイロビ', ['Nairobi']),
    city('mombasa', 'モンバサ', ['Mombasa']),
    city('kisumu', 'キスム', ['Kisumu']),
  ]),
  country('ci', 'コートジボワール', 'africa', [
    city('abidjan', 'アビジャン', ['Abidjan']),
    city('yamoussoukro', 'ヤムスクロ', ['Yamoussoukro']),
  ]),
  country('km', 'コモロ', 'africa'),
  country('cg', 'コンゴ共和国', 'africa', [
    city('brazzaville', 'ブラザビル', ['Brazzaville']),
    city('pointe-noire', 'ポワントノワール', ['Pointe-Noire']),
  ]),
  country('cd', 'コンゴ民主共和国', 'africa', [
    city('kinshasa', 'キンシャサ', ['Kinshasa']),
    city('lubumbashi', 'ルブンバシ', ['Lubumbashi']),
  ]),
  country('st', 'サントメ・プリンシペ', 'africa'),
  country('zm', 'ザンビア', 'africa', [
    city('lusaka', 'ルサカ', ['Lusaka']),
    city('ndola', 'ンドラ', ['Ndola']),
  ]),
  country('sl', 'シエラレオネ', 'africa', [city('freetown', 'フリータウン', ['Freetown'])]),
  country('dj', 'ジブチ', 'africa'),
  country('zw', 'ジンバブエ', 'africa', [
    city('harare', 'ハラレ', ['Harare']),
    city('bulawayo', 'ブラワヨ', ['Bulawayo']),
  ]),
  country('sd', 'スーダン', 'africa', [city('khartoum', 'ハルツーム', ['Khartoum'])]),
  country('sc', 'セーシェル', 'africa'),
  country('gq', '赤道ギニア', 'africa'),
  country('sn', 'セネガル', 'africa', [city('dakar', 'ダカール', ['Dakar'])]),
  country('so', 'ソマリア', 'africa'),
  country('tz', 'タンザニア', 'africa', [
    city('dar-es-salaam', 'ダルエスサラーム', ['Dar es Salaam']),
    city('dodoma', 'ドドマ', ['Dodoma']),
    city('arusha', 'アルーシャ', ['Arusha']),
    city('zanzibar', 'ザンジバル', ['Zanzibar']),
  ]),
  country('td', 'チャド', 'africa'),
  country('cf', '中央アフリカ', 'africa'),
  country('tn', 'チュニジア', 'africa', [
    city('tunis', 'チュニス', ['Tunis'], ['Tunisia']),
    city('sfax', 'スファックス', ['Sfax']),
  ]),
  country('tg', 'トーゴ', 'africa', [city('lome', 'ロメ', ['Lomé'])]),
  country('ng', 'ナイジェリア', 'africa', [
    city('lagos', 'ラゴス', ['Lagos']),
    city('abuja', 'アブジャ', ['Abuja']),
    city('ibadan', 'イバダン', ['Ibadan']),
  ]),
  country('na', 'ナミビア', 'africa', [city('windhoek', 'ウィントフック', ['Windhoek'])]),
  country('eh', '西サハラ', 'africa'),
  country('ne', 'ニジェール', 'africa', [city('niamey', 'ニアメ', ['Niamey'])]),
  country('bf', 'ブルキナファソ', 'africa', [city('ouagadougou', 'ワガドゥグ', ['Ouagadougou'])]),
  country('bi', 'ブルンジ', 'africa'),
  country('bj', 'ベナン', 'africa', [
    city('cotonou', 'コトヌー', ['Cotonou']),
    city('porto-novo', 'ポルトノボ', ['Porto-Novo']),
  ]),
  country('bw', 'ボツワナ', 'africa', [city('gaborone', 'ハボローネ', ['Gaborone'])]),
  country('mg', 'マダガスカル', 'africa', [city('antananarivo', 'アンタナナリボ', ['Antananarivo'])]),
  country('mw', 'マラウイ', 'africa', [
    city('lilongwe', 'リロングウェ', ['Lilongwe']),
    city('blantyre', 'ブランタイヤ', ['Blantyre']),
  ]),
  country('ml', 'マリ', 'africa', [city('bamako', 'バマコ', ['Bamako'])]),
  country('za', '南アフリカ', 'africa', [
    city('johannesburg', 'ヨハネスブルグ', ['ヨハネスブルク', 'Johannesburg']),
    city('cape-town', 'ケープタウン', ['Cape Town']),
    city('durban', 'ダーバン', ['Durban']),
    city('pretoria', 'プレトリア', ['Pretoria']),
    city('port-elizabeth', 'ポートエリザベス / グケベルハ', ['Port Elizabeth', 'Gqeberha']),
  ]),
  country('ss', '南スーダン', 'africa', [city('juba', 'ジュバ', ['Juba'])]),
  country('mu', 'モーリシャス', 'africa'),
  country('mr', 'モーリタニア', 'africa', [city('nouakchott', 'ヌアクショット', ['Nouakchott'])]),
  country('mz', 'モザンビーク', 'africa', [
    city('maputo', 'マプト', ['Maputo']),
    city('beira', 'ベイラ', ['Beira']),
  ]),
  country('ma', 'モロッコ', 'africa', [
    city('casablanca', 'カサブランカ', ['Casablanca']),
    city('rabat', 'ラバト', ['Rabat']),
    city('marrakech', 'マラケシュ', ['Marrakech']),
    city('fes', 'フェズ', ['Fès']),
    city('tangier', 'タンジェ', ['Tanger', 'Tangier']),
  ]),
  country('ly', 'リビア', 'africa', [city('tripoli', 'トリポリ', ['Tripoli'])]),
  country('lr', 'リベリア', 'africa', [city('monrovia', 'モンロビア', ['Monrovia'])]),
  country('rw', 'ルワンダ', 'africa', [city('kigali', 'キガリ', ['Kigali'])]),
  country('re', 'レユニオン（仏領）', 'africa', [], ['レユニオン']),
  country('ls', 'レソト', 'africa'),

  // その他
  country('aq', '南極', 'other'),
];

